### ISSUE TITLE
Color scheme with Babel syntax (red color for variables)

### ISSUE THREAD

**Issue by alexbeletsky** [equinusocio/material-theme#299]
For some reason, syntax coloring with Babel syntax looks differently, compare to plain JavaScript syntax.

With,

https://www.dropbox.com/s/hgpify2dptlgp3d/Screenshot%202015-07-06%2018.30.15.png?dl=0

Without,

https://www.dropbox.com/s/u8ssgokwyhza7xd/Screenshot%202015-07-06%2018.30.42.png?dl=0

As you can see, with Babel all variables and keywords are red.

Are there any fixes, workarounds for that?

**Comment by equinusocio** [comment]
This depends from the babel package provided scope. I can only fix this of the native js syntax.

**Comment by alexbeletsky** [comment]
@equinusocio Thanks a lot for your help.

I understand, but I'm using some other themes and the variables color isn't changed. Perhaps you know which babel's package file is responsible for this, so I can tweak it and maybe send PR to them.

**Comment by equinusocio** [comment]
I think other themes use a specific scope targetting for the color scheme. I will check if i can fix this.

**Comment by alexbeletsky** [comment]
I'm ready to help here, if you think it's applicable. I'm big fan of your theme, got used to that working with Atom, but want to switch back to ST3, cause Atom is a bit slow to me. To make it more clear, to reproduce issue:

1. Open any `.js` file, on right bottom you will see `JavaScript` as file type.
2. Assumed that [babel-sublime](https://github.com/babel/babel-sublime) is installed, switch to `Babel -> JavaScript (Babel)`.
3. All variables and keywords become red.

**Comment by equinusocio** [comment]
:+1:  thanks man

**Comment by alexbeletsky** [comment]
hey @equinusocio .. not pushing or anything, but have you had any progress with this? any clues, or I can help something?

**Comment by equinusocio** [comment]
@alexbeletsky i will fix it this week end

**Comment by equinusocio** [comment]
@alexbeletsky can you paste come babel snippets?

**Comment by equinusocio** [comment]
@alexbeletsky can you paste your code snippet? I think this is a problem with Babel Sublime scope.

**Comment by alexbeletsky** [comment]
It's applicable for any JS code, say

```
var app = express();
var env = process.env.NODE_ENV || 'development';
var port = process.env.PORT || 3010;

morgan.format('custom', ':method :url :status :res[content-length] - :response-time ms');
app.use(morgan('custom', {stream: logger.stream()}));
```

will give `app`, `env`, `port` be red color as on screenshot above. Can I give more details?

**Comment by equinusocio** [comment]
This is caused by the scope provided by Babel Sublime. The correct color scheme is the one with the  native Javascript syntax. I can't change the color scheme only for this package, otherwise i will have to do it with all syntax packages.

**Comment by alexbeletsky** [comment]
Thanks for info. Perhaps you know the place where babel package redefines that color, that seems to be wrong to me. Why that red color applied, anyway? Does babel say it is not "keyword" or something?

**Comment by joezimjs** [comment]
Babel's JS syntax highlighting changes the coloring of things for me no matter which color scheme I'm using. Babel's coloration on the Darker Material theme certainly is annoying, but I don't know that it would be classified as an issue with this color scheme.

**Comment by alexbeletsky** [comment]
It didn't change anything to me, I user [daylerees/colour-schemes](https://github.com/daylerees/colour-schemes) `peel` theme, also with [voronianski/oceanic-next-color-scheme](https://github.com/voronianski/oceanic-next-color-scheme) all is fine.. only with material-theme.

**Comment by equinusocio** [comment]
@alexbeletsky what do you mean with "all is fine"

**Comment by equinusocio** [comment]
Babel sublime update:

	Package Control Messages
	========================

	Babel:
	-----

	babel-sublime
	-------------
	
	Big improvements are coming soon to support flow type annotations. You may
	already start to notice some of them, like ES7 property initializers getting
	properly matched. But it's coming at a cost:
	
	There are currently two syntax definitions supporting different builds of
	Sublime Text 3 (ST2 doesn't work with either). One is the evolution of the
	other using Sublime's new "sublime-syntax" format. That new format allows for
	more complex matches, thus paving the way for flow support. If you're using
	Sublime Text 3 dev then you're already using the new syntax, if you're
	using the beta, then you're still using the old syntax.
	
	Here's the plan:
	
	1. Once the next Sublime Text 3 beta build comes out (whenever that is), I'll
	be removing the old syntax from the package. Since, that means that most
	(if not all) users will be able to use the new syntax. If you still need
	the old syntax, Don't Panic, you can clone the repo and run it like that.
	I'll put up instructions if that's thing someone wants.
	
	2. "Monokai Phoenix" will also go away. If you're running ST3 dev, and you're
	using Monokai Phoenix, you can already switch the stock Monokai and things
	will look mostly the same. The new syntax uses more generic scope names that
	make it more theme friendly.
	
	That's all.

**Comment by alexbeletsky** [comment]
What I meant is,

* [Daylerees Peel](https://www.dropbox.com/s/joluipbekujeb3r/Screenshot%202015-07-13%2021.28.55.png?dl=0)
* [Oceanic Next](https://www.dropbox.com/s/869ed17u1w074p4/Screenshot%202015-07-13%2021.29.29.png?dl=0)
* [Material](https://www.dropbox.com/s/uovo5ohjlqeb82a/Screenshot%202015-07-13%2021.32.07.png?dl=0)

All screenshots are done having "JavaScript (Babel)" syntax on.

**Comment by joezimjs** [comment]
It *is* interesting that the Material Design color scheme ends up being annoyingly red on something that usually lacks much color, but if you look at Oceanic Next with Babel and the built-in JavaScript syntax, you'll notice that they don't highlight everything the same way. This is just another one of those instances and Babel just happens to be interacting with Material Design in a way that tells it to use a highlight that is red.

**Comment by equinusocio** [comment]
Native ST js scope:
<img width="783" alt="native js" src="https://cloud.githubusercontent.com/assets/10454741/8660025/c7fdb50c-29ae-11e5-8c53-4ff2a87d9329.png">

Babel-Sublime scope:
<img width="810" alt="babel" src="https://cloud.githubusercontent.com/assets/10454741/8660026/c8025cb0-29ae-11e5-9df3-d91611182bc3.png">

what are we talking about? You don't like the red color for variable? All variables in material color schemes are red.

**Comment by joezimjs** [comment]
You must have a different "native JS" scope. Here's what mine looks like: 

![native js](https://cloud.githubusercontent.com/assets/1313898/8660649/cbe1bc7c-2977-11e5-9343-8dcc294395b0.png)

The variables are gray.

**Comment by joezimjs** [comment]
I wonder if you're using the dev edition of ST where they're updating the syntax highlighting.

**Comment by equinusocio** [comment]
Why variables should have a different color between Babel Js and Native JS? I'm usi ST 3 3098.

**Comment by joezimjs** [comment]
I'm using 3083. Let me try updating.

**Comment by joezimjs** [comment]
3083 is the latest version on the normal Beta channel (http://www.sublimetext.com/3). You must be on a later version in the Dev channel. 

> Build 3084
> Release Date: 8 April 2015
> - Added new Syntax Definition file format, .sublime-syntax

I wonder if the newer version of ST is using the newer Syntax Definition file format and therefore renders the highlighting differently than the current Beta version. So, in all likeliness, this issue will go away when ST updates on the Beta channel.

**Comment by equinusocio** [comment]
From babel-sublime message update:

> There are currently two syntax definitions supporting different builds of
Sublime Text 3 (ST2 doesn't work with either). One is the evolution of the
other using Sublime's new "sublime-syntax" format. That new format allows for
more complex matches, thus paving the way for flow support. If you're using
Sublime Text 3 dev then you're already using the new syntax, if you're
using the beta, then you're still using the old syntax.

**Comment by joezimjs** [comment]
Yes, I'm not worried about the babel one. I'm worried about the native JS one because that's the one that is different between us and you. I just updated my ST to the dev channel's latest build and now I'm seeing the red variables in the native JS's syntax highlighting. I'm pretty sure the whole issue is that @alexbeletsky and I were on older versions of ST.

**Comment by alexbeletsky** [comment]
> The variables are gray.

I also have all variables are gray in native "JavaScript" definition. I don't see that other packages are changing the color of variables depending on "JavaScript" or "JavaScript (Babel)".

If in new ST all variables are red.. well, it means I stay in Atom :) cause this I see Material should look like,

<img width="780" alt="screenshot 2015-07-13 23 16 57" src="https://cloud.githubusercontent.com/assets/304929/8661074/5478f27a-29b5-11e5-8d84-543126a19426.png">

**Comment by alexbeletsky** [comment]
Yes, I'm on stable version 3083.

**Comment by equinusocio** [comment]
@alexbeletsky 3083 is beta. However i don't think you should use one editor or another for his variables color...

**Comment by joezimjs** [comment]
So it can be considered a bug with Material Design theme because the older version of ST is using JavaScript.tmLanguage and the newer one is using JavaScript.sublime-syntax and there seems to be a difference that your theme isn't accounting for, but like I said, you can just put it off and assume that when .sublime-syntax lands on the Beta channel, the issue will be resolved.

**Comment by denizozger** [comment]
Just to clarify, can you confirm installing 3095 dev version should resolve this issue?

**Comment by deshiknaves** [comment]
I'm on 3095 the issue is not resolved. It is on the dark and light theme not on the default Material Theme.

**Comment by alexbeletsky** [comment]
I have adjusted the default theme to a) avoid red variables b) make it a little closer how atom version of material-ui on atom.

https://github.com/alexbeletsky/material-theme

It's just a quick correction with editor I did for myself, but if makes sense I can submit a PR. /cc @joezimjs @denizozger

**Comment by joezimjs** [comment]
Personally, I don't care anymore. I prefer to use Monokai since it's background is a slightly different color than the background used by the rest of the Material UI, so it's easier to distinguish barriers.

**Comment by denizozger** [comment]
@alexbeletsky I also stopped using this theme because of red variables (it's a terrible idea to get the attention to variables) but if your PR would be merged I'd switch back again.

**Comment by gj1118** [comment]
I see that you are using the darker version of the theme. I use the Monokai Extended https://github.com/jonschlinkert/sublime-monokai-extended color scheme with works very well with the darker version of the theme.

**Comment by joezimjs** [comment]
Thank @gj1118

**Comment by equinusocio** [comment]
Everyone is free to use the color scheme you prefer , but it's fun to see that a lot of people complain about an open source software instead of make PR.

@alexbeletsky let me see some screenshot about your fix.

**Comment by alexbeletsky** [comment]
There is sceenshot attached in my repo, that demostrates the changes I applied. In summary, no red variables and purple for keywords as `import`, `const`, `let`.. and very light-blue-grey for vars.

**Comment by equinusocio** [comment]
make a PR for darker, default and lighter version. Make sure that other languages looks right and i will merge your work. Thanks :+1:

**Comment by alexbeletsky** [comment]
Great, will pack a PR soon.

**Comment by equinusocio** [comment]
@alexbeletsky nice. Thanks for the help.

**Comment by TheSavior** [comment]
I'm also looking forward to babel syntax looking better (as @alexbeletsky describes) with this theme. I'm using Oceanic Next for now, but it doesn't go well with Material Dark.

**Comment by equinusocio** [comment]
@TheSavior you can use Oceanic Next with darker material theme by using:
```"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker-OceanicNext.tmTheme",```

**Comment by alexbeletsky** [comment]
@TheSavior sorry for delay, will submit PR asap

**Comment by alexbeletsky** [comment]
Happy to see it's merged. Just recieved an update, looks awesome.

**Comment by equinusocio** [comment]
@alexbeletsky i appreciate your work, but some people don't like the new colors. Can i ask you to reimplement the old syntax (with red variables) as alternative schemes? In the coming days I will not have much time.
