### ISSUE TITLE
Colour Issue

### ISSUE THREAD

**Issue by pingshunhuangalex** [equinusocio/material-theme#809]
It seems like the class name and the syntax "class" has the same highlighting color. Is it intentional? Thanks.
![image](https://cloud.githubusercontent.com/assets/17170199/15167091/2be02f7a-1769-11e6-8434-15a4bd150414.png)

**Comment by equinusocio** [comment]
I need you preferences, the syntax scope (language) and the used package for the code highlight

**Comment by n1ghtmare** [comment]
I've got the same issue, I'm using JavaScript (Babel) and here is how it looks like:

![capture123](https://cloud.githubusercontent.com/assets/3255810/15179300/dc63536e-178b-11e6-8659-fbd83ef7dc22.PNG)

**Comment by equinusocio** [comment]
I need some code snippet

**Comment by n1ghtmare** [comment]
Sure, here you go:

```
export default class HelloWorld extends Greeter {
	greet() {
		console.log("Hello World");
	}
}
```

**Comment by equinusocio** [comment]
With babel JS

<img width="471" alt="screen shot 2016-05-11 at 17 47 12" src="https://cloud.githubusercontent.com/assets/10454741/15187180/69d608d6-17a0-11e6-8028-806936e3aaed.png">

**Comment by n1ghtmare** [comment]
Not sure what to tell you, I've tested it (and can reproduce it on 3 different machines out of which one is a Mac) - the theme package is updated to the latest version.

**Comment by pingshunhuangalex** [comment]
Hi equinusocio

I tried n1ghtmare's snippet, but not luck either.
![image](https://cloud.githubusercontent.com/assets/17170199/15199921/9c118e1c-1825-11e6-90dd-b5dbf15f4f08.png)
I noticed the issue when I was using Python 3 creating a class. I didn't use any code highlight plugin other than the theme and the built-in ones. Please see my preference below:
```
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"dictionary": "Packages/Language - English/en_GB.dic",
	"dpi_scale": 1,
	"draw_minimap_border": true,
	"font_face": "Tsentsiu Mono HG",
	"font_options":
	[
		"gray_antialias",
		"subpixel_antialias"
	],
	"font_size": 12,
	"ignored_packages":
	[
		"GitGutter",
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_bold_tab": true,
	"material_theme_contrast_mode": true,
	"material_theme_panel_separator": true,
	"material_theme_tree_headings": true,
	"overlay_scroll_bars": "enabled",
	"show_encoding": true,
	"tab_size": 4,
	"theme": "Material-Theme-Darker.sublime-theme",
	"translate_tabs_to_spaces": true
}
```
And a screenshot on the packages I used:
![image](https://cloud.githubusercontent.com/assets/17170199/15199959/0187635c-1826-11e6-9c29-2cf5eccf27f6.png)
I'm using dark material theme with app bars, all in latest version. Hope these info can help with the diagnosis. Thanks.

**Comment by equinusocio** [comment]
I'm sorry but I can't reproduce this issue. I'm using ST build 3113 that include many syntax highlight fix
<img width="437" alt="screen shot 2016-05-12 at 10 30 23" src="https://cloud.githubusercontent.com/assets/10454741/15208610/d8df7104-182c-11e6-8dda-b63dca80b690.png">

This is what i see with the built-in javascript package:
<img width="427" alt="screen shot 2016-05-12 at 10 31 44" src="https://cloud.githubusercontent.com/assets/10454741/15208645/f4249ff2-182c-11e6-96c9-2f73f33320e2.png">

And this with the babel JS packages, both with the darker theme
<img width="443" alt="screen shot 2016-05-12 at 10 30 51" src="https://cloud.githubusercontent.com/assets/10454741/15208662/039a85aa-182d-11e6-8226-1c4e4224d799.png">

**Comment by pingshunhuangalex** [comment]
Hah, that could be the reason. I'm using stable version 3103, never tried dev version before. Thanks for the explanation. At least it brings me closure.

**Comment by alexbeletsky** [comment]
Is that possible at all to apply the fix for a stable version? I think the majority of people using it, instead of dev version.

**Comment by equinusocio** [comment]
I think no. This issue isn't related to the color scheme. There is some bugs in the previous ST build that break some scopes in syntaxes

**Comment by alexbeletsky** [comment]
Sorry, I don't get it.. The previous version of the package didn't have that issue (it has another one with attributes in JSX, that has been fixed). The version of ST didn't change for me. The conclusion is - `2.1.5` introduces a regression issue, which makes a keyword rendered with a different color. 

Where am I wrong?

**Comment by pingshunhuangalex** [comment]
Hi equinusocio

I just updated to 3113, but the issue remains so I don't think the problem is on ST's side...

**Comment by alexbeletsky** [comment]
Upgraded to 3114 now, still the same issue. But I just talked to colleague of mine, who is using the same theme - it looks correct on his machine, so maybe it's local problem.

**Comment by equinusocio** [comment]
@alexbeletsky are you using any SublimeLinter package?

**Comment by alexbeletsky** [comment]
@equinusocio yes, I do

<img width="456" alt="screenshot 2016-05-13 14 04 13" src="https://cloud.githubusercontent.com/assets/304929/15247306/af55ae24-1913-11e6-9e07-1f7b99c45590.png">

**Comment by equinusocio** [comment]
Try to remove or disable it and restart Sublime Text.

**Comment by alexbeletsky** [comment]
@equinusocio removed both linter packages, re-installed Material Theme, re-started Sublime, the issue **remains**. I see a comment by @pingshunhuangalex but it's not clear what exactly he did there to make it work.

**Comment by pingshunhuangalex** [comment]
@alexbeletsky 
Long story short...
1. Remove the theme.
2. Do a manual clean installation using repo here.
3. Use package control to overwrite the package to get the version no. and description instead of "unknown, no description"

**Comment by alexbeletsky** [comment]
@pingshunhuangalex @equinusocio just have completed same steps, issue **remains**.

**Comment by n1ghtmare** [comment]
@alexbeletsky Yeah, same here, issue remains. I use the stable build (but recently updated) - 3114. Didn't try a dev build.

**Comment by pingshunhuangalex** [comment]
@alexbeletsky 
Mmm, then I think our issues are not the same after all...
I found my solution by installing a brand-new ST, and installing packages one by one to narrow down the targets, and I suggest you do the same, even try a different computer. It's a big effort there, but I'm a visual animal and I can't lose the theme, so I went all the way around to get this done (Cost me a precious Saturday night and Sunday morning). I'm not sure how much you value these visual elements, balance it yourself. Best Wishes.

**Comment by equinusocio** [comment]
If you use SublimeLinter you have to clear the color scheme cache... 
http://www.sublimelinter.com/en/latest/usage.html#choosing-color-schemes

**Comment by alexbeletsky** [comment]
@equinusocio sorry, I know how annoying it sounds.. But, I did everything, cleared sublime-lint color cache, removed sublime-linter, removed material theme, installed everything again, but still having same results (function and const with wrong colors).

**Comment by pingshunhuangalex** [comment]
@alexbeletsky Have you tried the same steps on other computers?
If you only have one, try to download a portable version, and
1. Install package control
2. Do a manual installation of the package using the repo (not via package control, remember to change the folder name to material theme)
3. Check if the theme works for portable version. If it is, overwrite it using package control installation

**Comment by equinusocio** [comment]
@alexbeletsky try to grab your syntax package from [here](https://github.com/sublimehq/Packages) and put the folder inside your `Packages/User` directory.
